version: '3.9'

services:
  db:
    image: mariadb:11.3
    environment:
      MYSQL_ROOT_PASSWORD: gameoflife
      MYSQL_USER: gameoflife
      MYSQL_PASSWORD: gameoflife>
      MYSQL_DATABASE: game-of-life
    ports:
        - "3306:3306"
    volumes:
      - storage:/var/lib/mysql

volumes:
    storage: